spring:
  datasource:
    url: jdbc:postgresql://pellefant.db.elephantsql.com:5432/rqwpnndb
    username: rqwpnndb
    password: O7RNirlaQqFIDkrqC1Z6fMTDVktAEC6G
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
        temp.use_jdbc_metadata_defaults: false
